server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: pseudoproperty-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://postgresql_pseudoproperty-service:5432/PseudopropertyServiceDB
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      types:
        registration: hypersistence-utils
        json-dialect: true
    show-sql: false
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: beans

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

cache:
  memory:
    maxSize: 1000000000

logging:
  level:
    org.springframework.data: Info
    org.springframework.context.annotation: WARN
    org.springframework.boot.autoconfigure: WARN
    org.apache.kafka: WARN

permissions: true

service-level-access:
  restricted-to:
    - SUPER_ADMIN

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    display-request-duration: true
  api-docs:
    path: /v3/api-docs